#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Module my_coreNLP/test/data_long_sentences
# Author : SABLAYROLLES Louis
# Date : 28 / 05 / 17

# dataset test

tab = { 'small' : [
			"I did not. I did not. I do not say that.",
			"Secretary, is it President Obama's fault?",
			"You called it the gold standard of trade deals. You said it's the finest deal you've ever seen.",
			"Let me get you to pause right there, because we're going to move into -- we're going to move into the next segment. We're going to talk taxes...",
			"See, you're telling the enemy everything you want to do. No wonder you've been fighting -- no wonder you've been fighting ISIS your entire adult life.",
			"I don't mind releasing -- I'm under a routine audit. And it'll be released. And -- as soon as the audit's finished, it will be released.",
			"... of your taxes -- you're perfectly free to release your taxes during an audit. And so the question, does the public's right to know outweigh your personal...",
			"Maybe he didn't do a good job and I was unsatisfied with his work...",
			"Well, sometimes there's not a direct transfer of skills from business to government, but sometimes what happened in business would be really bad for government.",
			"No, the argument is that we have to take the guns away from these people that have them and they are bad people that shouldn't have them."
		],
		'medium' : [
			"And I have -- well, not quite that long. I think my husband did a pretty good job in the 1990s. I think a lot about what worked and how we can make it work again...",
			"Well, that is just not accurate. I was against it once it was finally negotiated and the terms were laid out. I wrote about that in...",
			"In fact, I have written a book about it. It's called \"Stronger Together\". You can pick it up tomorrow at a bookstore...",
			"Yeah, well, let's start the clock again, Lester. We've looked at your tax proposals. I don't see changes in the corporate tax rates or the kinds of proposals you're referring to that would cause the repatriation, bringing back of money that's stranded overseas. I happen to support that.",
			"I happen to -- I happen to support that in a way that will actually work to our benefit. But when I look at what you have proposed, you have what is called now the Trump loophole, because it would so advantage you and the business you do. You've proposed an approach that has a...",
			"I will. Look, the African-American community has been let down by our politicians. They talk good around election time, like right now, and after the election, they said, see ya later, I'll see you in four years. The African-American community -- because -- look, the community within the inner cities has been so badly treated. They've been abused and used in order to get votes by Democrat politicians, because that's what it is. They've controlled these communities for up to 100 years.",
			"I think -- I think -- I think Donald just criticized me for preparing for this debate. And, yes, I did. And you know what else I prepared for? I prepared to be president. And I think that's a good thing.",
			"You mention ISIS, and we think of ISIS certainly as over there, but there are American citizens who have been inspired to commit acts of terror on American soil, the latest incident, of course, the bombings we just saw in New York and New Jersey, the knife attack at a mall in Minnesota, in the last year, deadly attacks in San Bernardino and Orlando. I'll ask this to both of you. Tell us specifically how you would prevent homegrown attacks by American citizens, Mr. Trump?",
			"The record shows that I'm right. When I did an interview with Howard Stern, very lightly, first time anyone's asked me that, I said, very lightly, I don't know, maybe, who knows? Essentially. I then did an interview with Neil Cavuto. We talked about the economy is more important. I then spoke to Sean Hannity, which everybody refuses to call Sean Hannity. I had numerous conversations with Sean Hannity at Fox. And Sean Hannity said -- and he called me the other day -- and I spoke to him about it -- he said you were totally against the war, because he was for the war.",
			"And, in fact, his cavalier attitude about nuclear weapons is so deeply troubling. That is the number-one threat we face in the world. And it becomes particularly threatening if terrorists ever get their hands on any nuclear material. So a man who can be provoked by a tweet should not have his fingers anywhere near the nuclear codes, as far as I think anyone with any sense about this should be concerned.",
			"And she doesn't say that, because she's got no business ability. We need heart. We need a lot of things. But you have to have some basic ability. And sadly, she doesn't have that. All of the things that she's talking about could have been taken care of during the last 10 years, let's say, while she had great power. But they weren't taken care of. And if she ever wins this race, they won't be taken care of."
		],
		'long' : [
			"It's a great thing for companies to expand. And when these people are going to put billions and billions of dollars into companies, and when they're going to bring $2.5 trillion back from overseas, where they can't bring the money back, because politicians like Secretary Clinton won't allow them to bring the money back, because the taxes are so onerous, and the bureaucratic red tape, so what -- is so bad. So what they're doing is they're leaving our country, and they're, believe it or not, leaving because taxes are too high and because some of them have lots of money outside of our country. And instead of bringing it back and putting the money to work, because they can't work out a deal. We have a president that can't sit them around a table and get them to approve something. And here's the thing. Republicans and Democrats agree but we have no leadership. And honestly, that starts with Secretary Clinton.",
			"Typical politician. All talk, no action. Sounds good, doesn't work. Never going to happen. And we have a Fed that's doing political things. This Janet Yellen of the Fed. The Fed is doing political -- by keeping the interest rates at this level. And believe me: The day Obama goes off, and he leaves, and goes out to the golf course for the rest of his life to play golf, when they raise interest rates, you're going to see some very bad things happen, because the Fed is not doing their job.",
			"So if he's paid zero, that means zero for troops, zero for vets, zero for schools or health. And I think probably he's not all that enthusiastic about having the rest of our country see what the real reasons are, because it must be something really important, even terrible, that he's trying to hide. And I have no reason to believe that he's ever going to release his tax returns, because there's something he's hiding. The question is, were he ever to get near the White House, what would be those conflicts? Who does he owe money to? Well, he owes you the answers to that, and he should provide them.",
			"That was more than a mistake. That was done purposely. OK? That was not a mistake. That was done purposely. When you have your staff taking the Fifth Amendment, taking the Fifth so they're not prosecuted, when you have the man that set up the illegal server taking the Fifth, I think it's disgraceful. I am very underleveraged. I have a great company. I have a tremendous income. And the reason I say that is not in a braggadocios way. It's because it's about time that this country had somebody running it that has an idea about money. We're a debtor nation. We're a serious debtor nation. And we have a country that needs new roads, new tunnels, new bridges, new airports, new schools, new hospitals. And we don't have the money, because it's been squandered on so many of your ideas.",
			"Unfortunately, race still determines too much, often determines where people live, determines what kind of education in their public schools they can get, and, yes, it determines how they're treated in the criminal justice system. We have to restore trust between communities and the police. We have to work to make sure that our police are using the best training, the best techniques, that they're well prepared to use force only when necessary. There are so many good, brave police officers who equally want reform and we've got to get guns out of the hands of people who should not have them. We have to restore trust. We have to work with the police. We have to make sure they respect the communities and the communities respect them. And we have to tackle the plague of gun violence.",
			"I do want to bring up the fact that you were the one that brought up the words super-predator about young black youth. And that's a term that I think was a -- it's -- it's been horribly met, as you know. I think you've apologized for it. But I think it was a terrible thing to say. Stop-and-frisk, you know, you're talking about takes guns away. Well, I'm talking about taking guns away from gangs and people that use them. And I don't think -- I really don't think you disagree with me on this, if you want to know the truth. I think maybe there's a political reason why you can't say it, but I really don't believe -- in New York City, stop-and-frisk, we had 2,200 murders, and stop-and-frisk brought it down to 500 murders. Five hundred murders is a lot of murders. It's hard to believe, 500 is like supposed to be good? But we went from 2,200 to 500. But stop-and-frisk had a tremendous impact on the safety of New York City. Tremendous beyond belief.",
			"Well, just listen to what you heard. But it can't be dismissed that easily. He has really started his political activity based on this racist lie that our first black president was not an American citizen. But, remember, Donald started his career back in 1973 being sued by the Justice Department for racial discrimination because he would not rent apartments in one of his developments to African-Americans, and he made sure that the people who worked for him understood that was the policy. And the birther lie was a very hurtful one. You know, Barack Obama is a man of great dignity. And I could tell how much it bothered him and annoyed him that this was being touted and used against him. But I like to remember what Michelle Obama said in her amazing speech at our Democratic National Convention: When they go low, we go high. And Barack Obama went high, despite Donald Trump's best efforts to bring him down.",
			"First of all, I got to watch in preparing for this some of your debates against Barack Obama. You treated him with terrible disrespect. And I watched the way you talk now about how lovely everything is and how wonderful you are. It doesn't work that way. You were after him, you were trying to -- you even sent out or your campaign sent out pictures of him in a certain garb, very famous pictures. I don't think you can deny that. So when you tried to act holier than thou, it really doesn't work. It really doesn't. In Palm Beach, Florida, tough community, a brilliant community, a wealthy community, probably the wealthiest community there is in the world, I opened a club and no discrimination against African- Americans, against Muslims, against anybody. And it's a tremendously successful club. And I'm so glad I did it. And I have been given great credit for what I did. And I'm very, very proud of it. And that's the way I feel. That is the true way I feel.",
			"I don't think anybody knows it was Russia that broke into the DNC. She's saying Russia, Russia, Russia, but I don't -- maybe it was. I mean, it could be Russia, but it could also be China. It could also be lots of other people. It also could be somebody sitting on their bed that weighs 400 pounds, OK? But what did we learn with DNC? We learned that Bernie Sanders was taken advantage of by your people. Whether that was Russia, whether that was China, whether it was another country, we don't know, because the truth is, under President Obama we've lost control of things that we used to have control over.",
			"He actually advocated for the actions we took in Libya and urged that Gadhafi be taken out, after actually doing some business with him one time. George W. Bush made the agreement about when American troops would leave Iraq, not Barack Obama. The question you asked is, what do we do here in the United States? That's the most important part of this. So we've got to do everything we can to vacuum up intelligence from Europe, from the Middle East. That means we've got to work more closely with our allies, with our friends in the Middle East, many of which, as you know, are Muslim majority nations. Donald has consistently insulted Muslims abroad, Muslims at home, when we need to be cooperating with Muslim nations and with the American Muslim community. They're on the front lines. hey can provide information to us that we might not get anywhere else.",
			"We've been working with them for many years, and we have the greatest mess anyone's ever seen. You look at the Middle East, it's a total mess. Under your direction, to a large extent. But when you look at NATO. I said, and very strongly, NATO could be obsolete, because -- and I was very strong on this, and it was actually covered very accurately in the New York Times, which is unusual for the New York Times, to be honest -- but I said, they do not focus on terror. And about four months ago, I read on the front page of the Wall Street Journal that NATO is opening up a major terror division. And that was -- believe me -- I'm sure I'm not going to get credit for it -- but that was largely because of what I was saying and my criticism of NATO."
		]
	}
	
tab_segmented = { 'small' : [
					["I did not.", "I did not.", "I do not say that."],
					["Secretary, is it President Obama's fault?"],
					["You called it the gold standard of trade deals.", "You said it's the finest deal you've ever seen."],
					["Let me get you to pause right there," ,"because we're going to move into", "-- we're going to move into the next segment.", "We're going to talk taxes..."],
					["See, you're telling the enemy everything you want to do." ,"No wonder you've been fighting", "-- no wonder you've been fighting ISIS your entire adult life."],
					["I don't mind releasing", "-- I'm under a routine audit.", "And it'll be released.", "And -- as soon as the audit's finished, it will be released."],
					["... of your taxes -- you're perfectly free to release your taxes during an audit.", "And so the question, does the public's right to know outweigh your personal..."],
					["Maybe he didn't do a good job" ,"and I was unsatisfied with his work..."],
					["Well, sometimes there's not a direct transfer of skills from business to government,", "but sometimes what happened in business would be really bad for government."],
					["No, the argument is that we have to take the guns away from these people that have them ", "and they are bad people that shouldn't have them."]
				],
				'medium': [
					["And I have -- well, not quite that long.", "I think my husband did a pretty good job in the 1990s.", "I think a lot about what worked ", "and how we can make it work again..."],
					["Well, that is just not accurate.", "I was against it once it was finally negotiated and the terms were laid out.", "I wrote about that in..."],
					["In fact, I have written a book about it.", "It's called \"Stronger Together\".", "You can pick it up tomorrow at a bookstore..."],
					["Yeah, well, let's start the clock again, Lester.", "We've looked at your tax proposals.", "I don't see changes in the corporate tax rates or the kinds of proposals you're referring to that would cause the repatriation, bringing back of money that's stranded overseas.", "I happen to support that."],
					["I happen to", "-- I happen to support that in a way that will actually work to our benefit.", "But when I look at what you have proposed, you have what is called now the Trump loophole,", "because it would so advantage you and the business you do.", "You've proposed an approach that has a..."],
					["I will.", "Look, the African-American community has been let down by our politicians.", "They talk good around election time, like right now, and after the election, they said,", "see you later, I'll see you in four years.", "The African-American community -- because -- look, the community within the inner cities has been so badly treated.", "They've been abused and used in order to get votes by Democrat politicians,", "because that's what it is.", "They've controlled these communities for up to 100 years."],
					["I think ", "-- I think ", "-- I think Donald just criticized me for preparing for this debate.", "And, yes, I did.", "And you know what else I prepared for?", "I prepared to be president." ,"And I think that's a good thing."],
					["You mention ISIS,", "and we think of ISIS certainly as over there,", "but there are American citizens who have been inspired to commit acts of terror on American soil, the latest incident, of course,", "the bombings we just saw in New York and New Jersey,", "the knife attack at a mall in Minnesota,", "in the last year, deadly attacks in San Bernardino and Orlando.", "I'll ask this to both of you.", "Tell us specifically how you would prevent homegrown attacks by American citizens, Mr. Trump?"],
					["The record shows that I'm right.", "When I did an interview with Howard Stern, very lightly, first time anyone's asked me that,", "I said, very lightly,", "I don't know, maybe, who knows?", "Essentially.", "I then did an interview with Neil Cavuto.", "We talked about the economy is more important.", "I then spoke to Sean Hannity, which everybody refuses to call Sean Hannity.", "I had numerous conversations with Sean Hannity at Fox.", "And Sean Hannity said", "-- and he called me the other day", "-- and I spoke to him about it", "-- he said you were totally against the war,", "because he was for the war."],
					["And, in fact, his cavalier attitude about nuclear weapons is so deeply troubling.", "That is the number-one threat we face in the world.",  "And it becomes particularly threatening", "if terrorists ever get their hands on any nuclear material.", "So a man who can be provoked by a tweet should not have his fingers anywhere near the nuclear codes,", "as far as I think anyone with any sense about this should be concerned."],
					["And she doesn't say that,", "because she's got no business ability.", "We need heart.", "We need a lot of things.", "But you have to have some basic ability.", "And sadly, she doesn't have that.", "All of the things that she's talking about could have been taken care of during the last 10 years,", "let's say, while she had great power.", "But they weren't taken care of.", "And if she ever wins this race,", "they won't be taken care of."]
				]
				'long': [
					["It's a great thing for companies to expand.", "And when these people are going to put billions and billions of dollars into companies,", "and when they're going to bring $2.5 trillion back from overseas,", "where they can't bring the money back,", "because politicians like Secretary Clinton won't allow them to bring the money back,", "because the taxes are so onerous, and the bureaucratic red tape, so what -- is so bad.", "So what they're doing is they're leaving our country,", "and they're, believe it or not, leaving because taxes are too high and because some of them have lots of money outside of our country.", "And instead of bringing it back and putting the money to work,", "because they can't work out a deal.", "We have a president that can't sit them around a table and get them to approve something.", "And here's the thing.", "Republicans and Democrats agree", "but we have no leadership.", "And honestly, that starts with Secretary Clinton."],
					["Typical politician.", "All talk, no action.", "Sounds good, doesn't work.", "Never going to happen.", "And we have a Fed that's doing political things.", "This Janet Yellen of the Fed.", "The Fed is doing political", "-- by keeping the interest rates at this level.", "And believe me:", "The day Obama goes off, and he leaves, and goes out to the golf course for the rest of his life to play golf, when they raise interest rates,", "you're going to see some very bad things happen,", "because the Fed is not doing their job."],
					["So if he's paid zero,", "that means zero for troops, zero for vets, zero for schools or health.", "And I think probably he's not all that enthusiastic about having the rest of our country see what the real reasons are,", "because it must be something really important, even terrible, that he's trying to hide.", "And I have no reason to believe that he's ever going to release his tax returns,", "because there's something he's hiding.", "The question is, were he ever to get near the White House,", "what would be those conflicts?", "Who does he owe money to?", "Well, he owes you the answers to that, and he should provide them."],
					["That was more than a mistake.", "That was done purposely.", "OK?", "That was not a mistake.", "That was done purposely.", "When you have your staff taking the Fifth Amendment, taking the Fifth so they're not prosecuted,", "when you have the man that set up the illegal server taking the Fifth,", "I think it's disgraceful.", "I am very underleveraged.", "I have a great company.", "I have a tremendous income.", "And the reason I say that is not in a braggadocios way.", "It's because it's about time that this country had somebody running it that has an idea about money.", "We're a debtor nation.", "We're a serious debtor nation.", "And we have a country that needs new roads, new tunnels, new bridges, new airports, new schools, new hospitals.", "And we don't have the money,", "because it's been squandered on so many of your ideas."],
					["Unfortunately, race still determines too much, often determines where people live,",  "determines what kind of education in their public schools they can get,", "and, yes, it determines how they're treated in the criminal justice system.", "We have to restore trust between communities and the police.", "We have to work to make sure that our police are using the best training, the best techniques,", "that they're well prepared to use force only when necessary.", "There are so many good, brave police officers who equally want reform", "and we've got to get guns out of the hands of people who should not have them.", "We have to restore trust.", "We have to work with the police.", "We have to make sure they respect the communities and the communities respect them.", "And we have to tackle the plague of gun violence."],
					["I do want to bring up the fact that you were the one that brought up the words super-predator about young black youth.", "And that's a term that I think was a", "-- it's -- it's been horribly met,", "as you know.", "I think you've apologized for it.", "But I think it was a terrible thing to say.", "Stop-and-frisk, you know, you're talking about takes guns away.", "Well, I'm talking about taking guns away from gangs and people that use them.", "And I don't think", "-- I really don't think you disagree with me on this,", "if you want to know the truth.", "I think maybe there's a political reason why you can't say it,", "but I really don't believe", "-- in New York City, stop-and-frisk, we had 2,200 murders,", "and stop-and-frisk brought it down to 500 murders.", "Five hundred murders is a lot of murders.", "It's hard to believe, 500 is like supposed to be good?", "But we went from 2,200 to 500.", "But stop-and-frisk had a tremendous impact on the safety of New York City.",  "Tremendous beyond belief."],
					["Well, just listen to what you heard.", "But it can't be dismissed that easily.", "He has really started his political activity based on this racist lie", "that our first black president was not an American citizen.", "But, remember, Donald started his career back in 1973 being sued by the Justice Department for racial discrimination", "because he would not rent apartments in one of his developments to African-Americans,", "and he made sure that the people who worked for him understood that was the policy.", "And the birther lie was a very hurtful one.", "You know, Barack Obama is a man of great dignity.", "And I could tell how much it bothered him and annoyed him that this was being touted and used against him.", "But I like to remember what Michelle Obama said in her amazing speech at our Democratic National Convention:", "When they go low, we go high.", "And Barack Obama went high,", "despite Donald Trump's best efforts to bring him down."],
					["First of all, I got to watch in preparing for this some of your debates against Barack Obama.", "You treated him with terrible disrespect.", "And I watched the way you talk now about how lovely everything is and how wonderful you are.", "It doesn't work that way.", "You were after him, you were trying to", "-- you even sent out or your campaign sent out pictures of him in a certain garb, very famous pictures.", "I don't think you can deny that.", "So when you tried to act holier than thou,", "it really doesn't work.", "It really doesn't.", "In Palm Beach, Florida, tough community, a brilliant community, a wealthy community, probably the wealthiest community there is in the world,", "I opened a club and no discrimination against African- Americans, against Muslims, against anybody.", "And it's a tremendously successful club.", "And I'm so glad I did it.", "And I have been given great credit for what I did.", "And I'm very, very proud of it.", "And that's the way I feel.", "That is the true way I feel."],
					["I don't think anybody knows it was Russia that broke into the DNC.", "She's saying Russia, Russia, Russia, but I don't", "-- maybe it was.", "I mean, it could be Russia,", "but it could also be China.", "It could also be lots of other people.", "It also could be somebody sitting on their bed that weighs 400 pounds, OK?", "But what did we learn with DNC?", "We learned that Bernie Sanders was taken advantage of by your people.", "Whether that was Russia,", "whether that was China,", "whether it was another country,", "we don't know,", "because the truth is,", "under President Obama we've lost control of things", "that we used to have control over."],
					["He actually advocated for the actions we took in Libya and urged that Gadhafi be taken out,", "after actually doing some business with him one time.", "George W. Bush made the agreement about when American troops would leave Iraq, not Barack Obama.", "The question you asked is,", "what do we do here in the United States?", "That's the most important part of this.", "So we've got to do everything we can to vacuum up intelligence from Europe, from the Middle East.", "That means we've got to work more closely with our allies, with our friends in the Middle East, many of which,", "as you know, are Muslim majority nations.", "Donald has consistently insulted Muslims abroad, Muslims at home,", "when we need to be cooperating with Muslim nations and with the American Muslim community.", "They're on the front lines.", "They can provide information to us that we might not get anywhere else."],
					["We've been working with them for many years,", "and we have the greatest mess anyone's ever seen.", "You look at the Middle East, it's a total mess.", "Under your direction, to a large extent.", "But when you look at NATO.", "I said, and very strongly, NATO could be obsolete,", "because -- and I was very strong on this,", "and it was actually covered very accurately in the New York Times, which is unusual for the New York Times, to be honest --", "but I said, they do not focus on terror.", "And about four months ago, I read on the front page of the Wall Street Journal", "that NATO is opening up a major terror division.", "And that was", "-- believe me", "-- I'm sure I'm not going to get credit for it --"," but that was largely", "because of what I was saying and my criticism of NATO."]
				]
			}
	]